"""add origin codes to seller

Revision ID: 07fbc6f50282
Revises: 94458bf0d064
Create Date: 2026-03-15 14:00:04.138864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07fbc6f50282'
down_revision = '94458bf0d064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('province_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('province_code')
        batch_op.drop_column('community_code')

    # ### end Alembic commands ###
