"""add address relation to order

Revision ID: 4191a34f923d
Revises: 01b340eb84f8
Create Date: 2026-03-05 14:57:33.883198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4191a34f923d'
down_revision = '01b340eb84f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_address_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'address', ['shipping_address_id'], ['id'])
        batch_op.create_foreign_key(None, 'address', ['billing_address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('billing_address_id')
        batch_op.drop_column('shipping_address_id')

    # ### end Alembic commands ###
