"""empty message

Revision ID: 4925a9207819
Revises: 8945974ebd34
Create Date: 2026-02-21 19:36:14.373904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4925a9207819'
down_revision = '8945974ebd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('position', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('position', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('position', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcategory', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
