"""category_id nullable

Revision ID: 553642f62356
Revises: cf9ccc176449
Create Date: 2026-02-21 17:10:39.281756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553642f62356'
down_revision = 'cf9ccc176449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
