"""product name description to JSON

Revision ID: 6ec891846c7b
Revises: 3200034fd426
Create Date: 2026-02-23 19:23:07.154257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec891846c7b'
down_revision = '3200034fd426'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('product', schema=None) as batch_op:
#         batch_op.alter_column('name',
#                existing_type=sa.VARCHAR(length=200),
#                type_=sa.JSON(),
#                existing_nullable=False)
#         batch_op.alter_column('description',
#                existing_type=sa.VARCHAR(length=1000),
#                type_=sa.JSON(),
#                existing_nullable=True)

#     # ### end Alembic commands ###

def upgrade():
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('name',
            existing_type=sa.String(length=200),
            type_=sa.JSON(),
            postgresql_using='json_build_object(\'es\', name)',
            nullable=False
        )
        batch_op.alter_column('description',
            existing_type=sa.String(length=1000),
            type_=sa.JSON(),
            postgresql_using='CASE WHEN description IS NULL THEN NULL ELSE json_build_object(\'es\', description) END',
            nullable=True
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###
