"""empty message

Revision ID: 86f64df06ef3
Revises: cb8df640eb63
Create Date: 2026-02-21 12:41:27.748580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f64df06ef3'
down_revision = 'cb8df640eb63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('product_code_product_key'), type_='unique')
        batch_op.drop_column('code_product')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_product', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('product_code_product_key'), ['code_product'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
