"""add origin codes to seller

Revision ID: 94458bf0d064
Revises: 9da0699599c7
Create Date: 2026-03-15 11:03:26.835435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94458bf0d064'
down_revision = '9da0699599c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_community_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('origin_province_code', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_column('origin_province_code')
        batch_op.drop_column('origin_community_code')

    # ### end Alembic commands ###
