"""empty message

Revision ID: e2486f69dea1
Revises: c83695b5d544
Create Date: 2026-02-20 18:50:28.734289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2486f69dea1'
down_revision = 'c83695b5d544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
